In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
    ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2707, 6227, 666, 9641],
 [2707, 6227, 666, 3492],
 [2707, 2807, 666, 6590],
 [9873, 8084, 2705, 5210, 2153],
 [9873, 8084, 2705, 5210, 4476],
 [5671, 2707, 1288, 666, 9938],
 [9121, 1911, 1741, 5210]]

In [ ]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2707 6227  666 9641]
 [   0    0    0    0 2707 6227  666 3492]
 [   0    0    0    0 2707 2807  666 6590]
 [   0    0    0 9873 8084 2705 5210 2153]
 [   0    0    0 9873 8084 2705 5210 4476]
 [   0    0    0 5671 2707 1288  666 9938]
 [   0    0    0    0 9121 1911 1741 5210]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\emon1\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 486ms/step


array([[[-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [ 0.02842833, -0.01406129,  0.03849218, -0.04979625,
          0.01641433,  0.04243883,  0.0169812 , -0.01841973,
         -0.01759195, -0.01810206],
        [-0.01692034,  0.02246938,  0.00097597, -0.00309061,
         -0.03197696, -0.03912841, -0.0107704 ,  0.01140379,
         -0.0202571 ,  0.00645455],
        [ 0.04126879,  0.0142425 , -0.03168526, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2707, 6227,  666, 9641])

In [16]:
model.predict(np.array([embedded_docs[0]]))  # Wrap it in a list or array

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 522ms/step


array([[[-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [-0.02250229, -0.01567499,  0.01184778, -0.01407897,
          0.00241465,  0.00666957, -0.03401119,  0.03956569,
          0.03536751,  0.03385286],
        [ 0.02842833, -0.01406129,  0.03849218, -0.04979625,
          0.01641433,  0.04243883,  0.0169812 , -0.01841973,
         -0.01759195, -0.01810206],
        [-0.01692034,  0.02246938,  0.00097597, -0.00309061,
         -0.03197696, -0.03912841, -0.0107704 ,  0.01140379,
         -0.0202571 ,  0.00645455],
        [ 0.04126879,  0.0142425 , -0.03168526, -0.0